image: node:latest

stages:
  - build
  - test

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: build
  script:
    - pwd
    - cd user-management
    - npm install
  artifacts:
    paths:
      - node_modules/

testing_testing:
  stage: test
  script: 
    - pwd
    - cd user-management
    - npm test
