pipeline {
  environment {
  registry = "komalsingh54/training-tool"
  registryCredential = 'docker-hub'
  dockerImage = ''
  }
  agent any
  stages {
    stage('Cloning our Git') {
      steps {
        git 'https://github.com/komalsingh54/training-tool.git'
      }
    }
    stage('Building our image') {
      steps{
        dir('user-management') {
          script {
            dockerImage = docker.build registry + ":$BUILD_NUMBER"
          }
        }
      }
    }
    stage('Deploy our image') {
      steps{
        dir('user-management') {
          script {
            docker.withRegistry( '', registryCredential) {
            dockerImage.push()}
          }
        }
      }
    }
    stage('Cleaning up') {
      dir('user-management') {
        steps {
          sh "docker rmi $registry:$BUILD_NUMBER"
        }
      }
    }
  }
}
