pipeline {
  environment {
    registry = "komalsingh54/training-tool"
    registryCredential = 'docker-hub'
    dockerImage = ''
  }
  agent any
  stages {
    stage('Cloning our Git') {
      steps {
        git 'https://github.com/komalsingh54/training-tool.git'
      }
    }
    stage('Building our image') {
      steps{
        dir('user-management') {
          sh 'yarn install'
          sh 'yarn docker:build'
        }
      }
    }
    stage('push image') {
      steps{
        dir('user-management') {
          sh  "docker tag komalsingh54/user-management komalsingh54/user-management:$BUILD_NUMBER"
          sh  "docker push komalsingh54/training-tool:$BUILD_NUMBER"
        }
      }
    }
    stage('Cleaning up') {
      steps {
        dir('user-management') {
          sh "docker rmi komalsingh54/user-management:$BUILD_NUMBER"
        }
      }
    }
  }
}
